name: find_dmp
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-readr
  - conda-forge::r-dplyr
  - conda-forge::r-tibble
  - bioconda::bioconductor-champ
  - bioconda::bioconductor-lumi
  - bioconda::bioconductor-genelendatabase=1.28.0
  - bioconda::bioconductor-illuminahumanmethylationepicv2manifest
  - bioconda::bioconductor-minfi
  - bioconda::bioconductor-illuminahumanmethylation450kmanifest
  - bioconda::bioconductor-IlluminaHumanMethylation450kanno.ilmn12.hg19
  - anaconda::libopenblas=0.3.3
  - conda-forge::r-rio
