name: sex_chromosomes
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-illuminahumanmethylationepicv2manifest
  - bioconda::bioconductor-minfi
  - bioconda::bioconductor-IlluminaHumanMethylation450kanno.ilmn12.hg19=0.6.1
  - bioconda::bioconductor-illuminahumanmethylationepicv2anno.20a1.hg38
  - bioconda::bioconductor-illuminahumanmethylation450kmanifest=0.4.0
  - conda-forge::r-tibble
  - bioconda::bioconductor-flowsorted.blood.epic
  - bioconda::bioconductor-flowsorted.blood.450k
  - anaconda::libopenblas=0.3.3
