name: sex_chromosomes
channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-illuminahumanmethylationepicmanifest=0.3.0
- bioconda::bioconductor-minfi
- bioconda::bioconductor-IlluminaHumanMethylation450kanno.ilmn12.hg19=0.6.1
- bioconda::bioconductor-illuminahumanmethylationepicanno.ilm10b2.hg19
- bioconda::bioconductor-illuminahumanmethylation450kmanifest=0.4.0
- conda-forge::r-tibble
- bioconda::bioconductor-flowsorted.blood.epic
- bioconda::bioconductor-flowsorted.blood.450k
- anaconda::libopenblas=0.3.3