name: cell_composition
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-readr
  - bioconda::bioconductor-champ
  - bioconda::bioconductor-lumi
  - bioconda::bioconductor-genelendatabase=1.28.0
