name: xreactive_probes
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-illuminahumanmethylationepicv2manifest
  - bioconda::bioconductor-minfi
  - bioconda::bioconductor-illuminahumanmethylation450kmanifest
  - bioconda::bioconductor-IlluminaHumanMethylation450kanno.ilmn12.hg19
  - anaconda::libopenblas
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-missmethyl
  - bioconda::bioconductor-dmrcate
  - bioconda::bioconductor-minfidata
  - conda-forge::r-stringi
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19.masked
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg38.masked=1.3.993
  - bioconda::bioconductor-watermelon
